/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.pep.ifsp.edu.view;

import br.pep.ifsp.edu.controller.VehicleController;
import br.pep.ifsp.edu.enums.Status;
import br.pep.ifsp.edu.model.Vehicle;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author george
 */
public class CadastreForm extends javax.swing.JFrame {

    
    private VehicleController vehicleController;
    
    public CadastreForm() {
        initComponents();
        this.vehicleController = new VehicleController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelValue = new javax.swing.JPanel();
        textValue = new javax.swing.JTextField();
        painelDescription = new javax.swing.JPanel();
        textDescription = new javax.swing.JTextField();
        painelYear = new javax.swing.JPanel();
        textYear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonCadastre = new javax.swing.JPanel();
        cadastrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textStatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonClear = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 0, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/car3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(106, 106, 106))
        );

        jLabel2.setBackground(new java.awt.Color(102, 0, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 255));
        jLabel2.setText("Cadastrar Veículos");

        painelValue.setBackground(new java.awt.Color(255, 255, 255));
        painelValue.setForeground(new java.awt.Color(51, 51, 51));

        textValue.setBackground(new java.awt.Color(255, 255, 255));
        textValue.setForeground(new java.awt.Color(153, 153, 153));
        textValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout painelValueLayout = new javax.swing.GroupLayout(painelValue);
        painelValue.setLayout(painelValueLayout);
        painelValueLayout.setHorizontalGroup(
            painelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textValue))
        );
        painelValueLayout.setVerticalGroup(
            painelValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelValueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textValue, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelDescription.setBackground(new java.awt.Color(255, 255, 255));
        painelDescription.setForeground(new java.awt.Color(51, 51, 51));

        textDescription.setBackground(new java.awt.Color(255, 255, 255));
        textDescription.setForeground(new java.awt.Color(153, 153, 153));
        textDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout painelDescriptionLayout = new javax.swing.GroupLayout(painelDescription);
        painelDescription.setLayout(painelDescriptionLayout);
        painelDescriptionLayout.setHorizontalGroup(
            painelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelDescriptionLayout.setVerticalGroup(
            painelDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDescription)
                .addContainerGap())
        );

        painelYear.setBackground(new java.awt.Color(255, 255, 255));
        painelYear.setForeground(new java.awt.Color(51, 51, 51));

        textYear.setBackground(new java.awt.Color(255, 255, 255));
        textYear.setForeground(new java.awt.Color(153, 153, 153));
        textYear.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout painelYearLayout = new javax.swing.GroupLayout(painelYear);
        painelYear.setLayout(painelYearLayout);
        painelYearLayout.setHorizontalGroup(
            painelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelYearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textYear, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelYearLayout.setVerticalGroup(
            painelYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelYearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(102, 0, 255));
        jLabel3.setForeground(new java.awt.Color(102, 0, 255));
        jLabel3.setText("Descrição");

        jLabel4.setForeground(new java.awt.Color(102, 0, 255));
        jLabel4.setText("Ano");

        jLabel5.setForeground(new java.awt.Color(102, 0, 255));
        jLabel5.setText("Valor");

        buttonCadastre.setBackground(new java.awt.Color(102, 0, 255));
        buttonCadastre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastreMouseClicked(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("CADASTRAR");

        javax.swing.GroupLayout buttonCadastreLayout = new javax.swing.GroupLayout(buttonCadastre);
        buttonCadastre.setLayout(buttonCadastreLayout);
        buttonCadastreLayout.setHorizontalGroup(
            buttonCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonCadastreLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cadastrar)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        buttonCadastreLayout.setVerticalGroup(
            buttonCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonCadastreLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        textStatus.setBackground(new java.awt.Color(255, 255, 255));
        textStatus.setForeground(new java.awt.Color(153, 153, 153));
        textStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textStatus)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textStatus)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(102, 0, 255));
        jLabel6.setForeground(new java.awt.Color(102, 0, 255));
        jLabel6.setText("Status");

        buttonClear.setBackground(new java.awt.Color(102, 0, 255));
        buttonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LIMPAR");

        javax.swing.GroupLayout buttonClearLayout = new javax.swing.GroupLayout(buttonClear);
        buttonClear.setLayout(buttonClearLayout);
        buttonClearLayout.setHorizontalGroup(
            buttonClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonClearLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        buttonClearLayout.setVerticalGroup(
            buttonClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonClearLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(painelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(painelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(painelYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCadastre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCadastre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //validação de daados
    public Boolean validationDate(String description, String year, String value, String status){
        if(description.trim().equals("") || year.trim().equals("") || value.trim().equals("") || status.trim().equals("")){
            return true;
        }
        return false;
    }
    private void buttonCadastreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastreMouseClicked

        Vehicle vehicle = new Vehicle();
        String description = textDescription.getText();
        String year = textYear.getText();
        String value = textValue.getText();
        String status = textStatus.getText().toUpperCase();
        
        BigDecimal valueConvert = new BigDecimal(value);
        
        vehicle.setDescription(description);
        vehicle.setYear(Integer.valueOf(year));
        vehicle.setValue(valueConvert);
        vehicle.setDate(new Date());
        
        if(status.toUpperCase().equals("DISPONIVEL")){
            vehicle.setStatus(Status.DISPONIVEL);
        }else{
            vehicle.setStatus(Status.ALUGADO);
        }
       
        
        if(validationDate(description, year, value, status)){
           JOptionPane.showMessageDialog(null, "Preencha os campos obrigatorios", "Alert", JOptionPane.WARNING_MESSAGE);
            
        }else{
            
            try {
                this.vehicleController.insertVehicle(vehicle);
                JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso");
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
            
        
    }//GEN-LAST:event_buttonCadastreMouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        textDescription.setText("");
        textYear.setText("");
        textValue.setText("");
        textStatus.setText("");
    }//GEN-LAST:event_buttonClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonCadastre;
    private javax.swing.JPanel buttonClear;
    private javax.swing.JLabel cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelDescription;
    private javax.swing.JPanel painelValue;
    private javax.swing.JPanel painelYear;
    private javax.swing.JTextField textDescription;
    private javax.swing.JTextField textStatus;
    private javax.swing.JTextField textValue;
    private javax.swing.JTextField textYear;
    // End of variables declaration//GEN-END:variables
}
